services:
  # Upstash cache mock
  redis:
    image: redis
    command: ["redis-server", "--loglevel", "verbose"]
    ports:
      - "6379:6379"
  srh:
    image: hiett/serverless-redis-http:latest
    ports:
      - "8079:80"
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://redis:6379"
